# 期刊 {#jcr}

## ESI学科认定的期刊
也就说，你投这些期刊，才是服从学科了

```{r}
pick_discipline <- c("Engineering", "Computer Science", "Chemistry")
colnames(tidyESI::esi_jcr_list)
```


比如物理学科，你投这些期刊，在川师的话你会自摸加一番

```{r}
tidyESI::esi_jcr_list %>% 
  janitor::clean_names() %>% 
  dplyr::mutate(
    across(category_name, stringr::str_to_title)
  ) %>% 
  dplyr::filter(category_name %in% c("Physics")) %>% 
  dplyr::select(category_name, full_title, issn) %>% 

  head(15) %>%
  knitr::kable(
    caption = "优秀的物理期刊",
    booktabs = TRUE
  ) %>%
  kableExtra::kable_styling(latex_options = "hold_position")

```




```{r, eval=FALSE}
tidyESI::esi_jcr_list %>% 
  janitor::clean_names() %>% 
  dplyr::mutate(
    across(category_name, stringr::str_to_title)
  ) %>% 
  dplyr::filter(category_name %in% pick_discipline) %>% 
  dplyr::select(category_name, full_title, issn) %>% 
  dplyr::arrange(category_name) %>% 
  
  
  dplyr::group_by(category_name, .drop = FALSE) %>%
  dplyr::group_walk(
    ~readr::write_excel_csv(.x, path = glue::glue("{.y}.xlsx"))
   )
```



## 影响因子

```{r}
df <- 
  readxl::read_excel("./data_JCR/JournalHomeGrid.xlsx", skip = 2) %>% 
  janitor::clean_names() %>% 
  dplyr::select(rank, 
                full_title = full_journal_title, 
                total_cites, 
                journal_impact_factor, 
                eigenfactor_score) %>% 
  dplyr::filter(!is.na(full_title)) %>% 
  dplyr::mutate(
    across(full_title, stringr::str_to_title) 
  ) 
  

tb <- tidyESI::esi_jcr_list 



d <- df %>% dplyr::left_join(tb, by = "full_title") #目的是要知道每个期刊的ESI学科分类
```




化学学科的期刊列表，包括期刊的影响因子
```{r}
Engineering_list <- d %>% 
  dplyr::filter(discipline == "Engineering") %>% 
  dplyr::select(discipline, rank, full_title, journal_impact_factor, issn)

Engineering_list %>% 
  head(5)

#Engineering_list %>% write_rds("engineering_journal_list.rds")

```

